install:
  - set QTDIR=C:\Qt\5.11.3\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake lifetime3.pro
  - mingw32-make
  - 7z a lifetime.zip C:/projects/lifetime/bin/lifetime.exe
artifacts:
  - path: lifetime.zip
    name: Lifetime
